CREATE TABLE RSS(
    URL VARCHAR(255) PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MARK VARCHAR(255) NOT NULL,
    ACTIVE DEFAULT 1
);

CREATE TABLE SUB(
    URL VARCHAR(255) NOT NULL,
    CHAT_ID CHARACTER(20) NOT NULL,
    PRIMARY KEY(URL,CHAT_ID)
);
