CREATE TABLE "RSS" (
	"URL"	VARCHAR(255) NOT NULL,
	"TITLE"	VARCHAR(255) NOT NULL,
	"MARK"	VARCHAR(255) NOT NULL,
	"ACTIVE"	TEXT DEFAULT 1,
	PRIMARY KEY("URL")
);

CREATE TABLE "SUB" (
	"URL"	VARCHAR(255) NOT NULL,
	"CHAT_ID"	CHARACTER(20) NOT NULL,
	"NICKNAME"	VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY("URL","CHAT_ID")
);

CREATE TRIGGER IF NOT EXISTS UPDATE_NICKNAME 
AFTER INSERT 
ON SUB
WHEN (NEW.NICKNAME) ISNULL
BEGIN
    UPDATE SUB SET SUB.NICKNAME = RSS.TITLE WHERE SUB.URL=RSS.URL;
END;